
// src/components/ai/chat-view.tsx
"use client";

import React, { useState, useRef, useEffect } from 'react';
import type { ChatMessage } from '@/types/ai-chat';
import { Button } from '@/components/ui/button';
import { Textarea } from '@/components/ui/textarea';
import { ScrollArea } from '@/components/ui/scroll-area';
import { Send, User, Bot, Image as ImageIcon, AlertCircle, Loader2, MessageSquareText } from 'lucide-react';
import NextImage from 'next/image';
import { askStudyAssistant, type StudyAssistantInput, type StudyAssistantOutput } from '@/ai/flows/study-assistant-flow';
import { useToast } from '@/hooks/use-toast';
import { Avatar, AvatarFallback, AvatarImage } from '@/components/ui/avatar'; // Avatar imported
import { format } from 'date-fns';
import { es } from 'date-fns/locale';
import { Skeleton } from '../ui/skeleton';

interface ChatViewProps {
  messages: ChatMessage[];
  activeSessionId: string | null;
  onSendMessage: (sessionId: string, message: Omit<ChatMessage, 'id' | 'timestamp'>) => string; // Returns new messageId
  onUpdateMessage: (sessionId: string, messageId: string, updates: Partial<ChatMessage>) => void;
  currentLanguage: 'es' | 'en';
}

export function ChatView({
  messages,
  activeSessionId,
  onSendMessage,
  onUpdateMessage,
  currentLanguage,
}: ChatViewProps) {
  const [inputValue, setInputValue] = useState('');
  const [isResponding, setIsResponding] = useState(false);
  const { toast } = useToast();
  const scrollAreaRef = useRef<HTMLDivElement>(null);
  const inputRef = useRef<HTMLTextAreaElement>(null);

  const T = {
    es: {
      inputPlaceholder: "Escribe tu pregunta para Nova...",
      sendMessage: "Enviar mensaje a Nova",
      assistantErrorTitle: "Error del Asistente Nova",
      assistantErrorMessage: "Nova tuvo un problema al procesar tu solicitud.",
      imageAlt: "Imagen generada por Nova",
      suggestionsTitle: "Nova sugiere:",
      loadingNova: "Nova está pensando...",
      noActiveChat: "Selecciona o crea un chat para comenzar.",
      messageFrom: "Mensaje de",
      atTime: "a las",
    },
    en: {
      inputPlaceholder: "Type your question for Nova...",
      sendMessage: "Send message to Nova",
      assistantErrorTitle: "Nova Assistant Error",
      assistantErrorMessage: "Nova had an issue processing your request.",
      imageAlt: "Image generated by Nova",
      suggestionsTitle: "Nova suggests:",
      loadingNova: "Nova is thinking...",
      noActiveChat: "Select or create a chat to start.",
      messageFrom: "Message from",
      atTime: "at",
    }
  }[currentLanguage];

  useEffect(() => {
    if (scrollAreaRef.current) {
      const scrollViewport = scrollAreaRef.current.querySelector('[data-radix-scroll-area-viewport]');
      if (scrollViewport) {
        scrollViewport.scrollTop = scrollViewport.scrollHeight;
      }
    }
  }, [messages]);

  useEffect(() => {
    inputRef.current?.focus();
  }, [activeSessionId]);


  const handleSendMessage = async (queryOverride?: string) => {
    if (!activeSessionId) return;
    const currentQuery = (queryOverride || inputValue).trim();
    if (!currentQuery || isResponding) return;

    onSendMessage(activeSessionId, { type: 'user', text: currentQuery });
    setInputValue('');
    setIsResponding(true);

    const assistantLoadingMessageId = onSendMessage(activeSessionId, { type: 'assistant', isLoading: true });

    const lowerQuery = currentQuery.toLowerCase();
    const generateImageExplicitly =
      lowerQuery.includes("imagen") ||
      lowerQuery.includes("dibuj") ||
      lowerQuery.includes("diagrama") ||
      lowerQuery.includes("mapa") ||
      lowerQuery.includes("visual") ||
      lowerQuery.includes("picture") ||
      lowerQuery.includes("draw") ||
      lowerQuery.includes("diagram") ||
      lowerQuery.includes("map");

    try {
      const assistantInput: StudyAssistantInput = {
        query: currentQuery,
        language: currentLanguage,
        generateImageExplicitly,
      };
      const assistantResponse: StudyAssistantOutput = await askStudyAssistant(assistantInput);

      onUpdateMessage(activeSessionId, assistantLoadingMessageId, {
        text: assistantResponse.mainResponse,
        imageUrl: assistantResponse.generatedImageUrl,
        imageQuery: assistantResponse.imageQuerySuggestion,
        suggestions: assistantResponse.followUpSuggestions,
        isLoading: false,
      });

    } catch (error: any) {
      console.error('Error calling study assistant:', error);
      const errorMessageText = error.message || T.assistantErrorMessage;
      toast({
        variant: 'destructive',
        title: T.assistantErrorTitle,
        description: errorMessageText,
      });
      onUpdateMessage(activeSessionId, assistantLoadingMessageId, {
        text: errorMessageText,
        isLoading: false,
      });
    } finally {
      setIsResponding(false);
      inputRef.current?.focus();
    }
  };

  const handleSuggestionClick = (suggestion: string) => {
    handleSendMessage(suggestion);
  };

  if (!activeSessionId) {
    return (
      <div className="flex flex-col h-full items-center justify-center p-4 text-center">
        <MessageSquareText className="h-16 w-16 text-muted-foreground mb-4" />
        <p className="text-lg font-medium text-foreground">{T.noActiveChat}</p>
        <p className="text-sm text-muted-foreground">
          {currentLanguage === 'es' ? 'Usa el panel de la izquierda para empezar una nueva conversación o seleccionar una existente.' : 'Use the panel on the left to start a new conversation or select an existing one.'}
        </p>
      </div>
    );
  }

  return (
    <div className="flex flex-col h-full">
      <ScrollArea className="flex-grow p-4 overflow-y-auto" ref={scrollAreaRef}>
        <div className="space-y-4 mb-4">
          {messages.map((msg) => (
            <div
              key={msg.id}
              className={`flex items-start gap-3 ${
                msg.type === 'user' ? 'justify-end' : 'justify-start'
              }`}
            >
              {msg.type === 'assistant' && (
                <Avatar className="h-8 w-8 bg-primary text-primary-foreground flex items-center justify-center shrink-0">
                  <Bot className="h-5 w-5" />
                </Avatar>
              )}
              <div
                className={`max-w-[80%] rounded-lg px-3.5 py-2.5 shadow-sm ${
                  msg.type === 'user'
                    ? 'bg-primary text-primary-foreground rounded-br-none'
                    : 'bg-card text-card-foreground border border-border rounded-bl-none'
                }`}
              >
                {msg.isLoading ? (
                  <div className="flex items-center space-x-2 p-1">
                    <span className="text-sm italic">{T.loadingNova}</span>
                    <Loader2 className="h-4 w-4 animate-spin" />
                  </div>
                ) : (
                  <>
                    {msg.text && <p className="text-sm whitespace-pre-wrap" dangerouslySetInnerHTML={{ __html: msg.text.replace(/\n/g, '<br />') }}></p>}
                    {msg.imageUrl && (
                      <div className="mt-2 p-1 bg-background/50 rounded-md">
                        <NextImage
                          src={msg.imageUrl}
                          alt={msg.imageQuery || T.imageAlt}
                          width={300}
                          height={200}
                          className="rounded-md object-contain max-h-[300px] w-auto"
                          data-ai-hint={msg.imageQuery || "abstract illustration"}
                        />
                      </div>
                    )}
                    {msg.suggestions && msg.suggestions.length > 0 && (
                      <div className="mt-3 pt-2 border-t border-border/20 space-y-1.5">
                        <p className="text-xs font-medium text-muted-foreground/80">
                          {T.suggestionsTitle}
                        </p>
                        <div className="flex flex-wrap gap-1.5">
                          {msg.suggestions.map((sugg, index) => (
                            <Button
                              key={`${msg.id}-sugg-${index}`}
                              variant="outline"
                              size="sm"
                              className="text-xs h-auto py-1 px-2 border-primary/50 text-primary hover:bg-primary/10"
                              onClick={() => handleSuggestionClick(sugg)}
                            >
                              {sugg}
                            </Button>
                          ))}
                        </div>
                      </div>
                    )}
                  </>
                )}
                 <p className="text-xs text-muted-foreground/70 mt-1.5 text-right">
                  {format(msg.timestamp, 'p', { locale: currentLanguage === 'es' ? es : undefined })}
                </p>
              </div>
              {msg.type === 'user' && (
                <Avatar className="h-8 w-8 bg-secondary text-secondary-foreground flex items-center justify-center shrink-0">
                  {/* You can use a user profile image here if available */}
                  <User className="h-5 w-5" />
                </Avatar>
              )}
            </div>
          ))}
        </div>
      </ScrollArea>
      <div className="p-3 border-t border-border bg-background">
        <form
          onSubmit={(e) => {
            e.preventDefault();
            handleSendMessage();
          }}
          className="flex w-full items-end gap-2"
        >
          <Textarea
            ref={inputRef}
            placeholder={T.inputPlaceholder}
            value={inputValue}
            onChange={(e) => setInputValue(e.target.value)}
            onKeyDown={(e) => {
              if (e.key === 'Enter' && !e.shiftKey && !isResponding) {
                e.preventDefault();
                handleSendMessage();
              }
            }}
            rows={1}
            className="min-h-[44px] max-h-[150px] flex-grow resize-none bg-input border-input pr-12 text-sm"
            disabled={isResponding}
          />
          <Button type="submit" size="icon" disabled={isResponding || !inputValue.trim()} aria-label={T.sendMessage} className="h-11 w-11">
            <Send className="h-5 w-5" />
          </Button>
        </form>
      </div>
    </div>
  );
}
